-- test comment
CREATE SCHEMA RJB_BLOG_MULTITENANCY_1;

-- a single application 'Product' table
CREATE TABLE RJB_BLOG_MULTITENANCY_1.PRODUCT  (
   id INT GENERATED BY DEFAULT AS IDENTITY,
   version INT DEFAULT 1 NOT NULL,
   created_user VARCHAR(255) NOT NULL,
   created_timestamp TIMESTAMP NOT NULL,
   updated_user VARCHAR(255) NOT NULL,
   updated_timestamp TIMESTAMP NOT NULL,
   category VARCHAR(255) NOT NULL,
   sku VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX RJB_BLOG_MULTITENANCY_1.IDX_PRODUCT_SKU ON RJB_BLOG_MULTITENANCY_1.PRODUCT (sku);

-- create a single test user 
CREATE USER "rjb-blog-mutlitenancy-1" PASSWORD 'rjb-blog-mutlitenancy-1';

-- grant CRUD access our 'Product' table for the single test user
GRANT SELECT, INSERT, UPDATE, DELETE ON RJB_BLOG_MULTITENANCY_1.PRODUCT TO "rjb-blog-mutlitenancy-1";

-- mock Product(s)
INSERT INTO RJB_BLOG_MULTITENANCY_1.PRODUCT (id, created_user, created_timestamp, updated_user, updated_timestamp, category, sku) 
VALUES (1, 'rjb-multitenancy-blog', CURRENT_TIMESTAMP, 'rjb-multitenancy-blog', CURRENT_TIMESTAMP, 'Test Category', 'SKU-1');

INSERT INTO RJB_BLOG_MULTITENANCY_1.PRODUCT (id, created_user, created_timestamp, updated_user, updated_timestamp, category, sku) 
VALUES (2, 'rjb-multitenancy-blog', CURRENT_TIMESTAMP, 'rjb-multitenancy-blog', CURRENT_TIMESTAMP, 'Test Category', 'SKU-2');

INSERT INTO RJB_BLOG_MULTITENANCY_1.PRODUCT (id, created_user, created_timestamp, updated_user, updated_timestamp, category, sku) 
VALUES (3, 'rjb-multitenancy-blog', CURRENT_TIMESTAMP, 'rjb-multitenancy-blog', CURRENT_TIMESTAMP, 'Test Category 2', 'SKU-3');

